# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pisa.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 720)
        MainWindow.setMinimumSize(QtCore.QSize(850, 720))
        MainWindow.setMaximumSize(QtCore.QSize(850, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/open/Icons/ppd_enhanced_colors_supreme-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(200, 200, 200);\n"
"font: 75 11pt \"Verdana\";\n"
"color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_menu_principal = QtWidgets.QFrame(self.centralwidget)
        self.frame_menu_principal.setMaximumSize(QtCore.QSize(16777215, 110))
        self.frame_menu_principal.setStyleSheet("background-color: rgb(100, 100, 100,200);")
        self.frame_menu_principal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_menu_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_principal.setObjectName("frame_menu_principal")
        self.pushButton_open = QtWidgets.QPushButton(self.frame_menu_principal)
        self.pushButton_open.setGeometry(QtCore.QRect(13, 2, 80, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_open.sizePolicy().hasHeightForWidth())
        self.pushButton_open.setSizePolicy(sizePolicy)
        self.pushButton_open.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_open.setFont(font)
        self.pushButton_open.setToolTipDuration(-2)
        self.pushButton_open.setStyleSheet("QPushButton{\n"
"    \n"
"    background-image: url(:/open/pasta_icon-removebg-preview.png);\n"
"    background-color:transparent;\n"
"    background-repeat:no-repeat;\n"
"    background-position:center;\n"
"    background-size-height:80px;\n"
"    background-size-width:80px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 255, 255);    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.pushButton_open.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/open/Icons/pasta_icon-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_open.setIcon(icon1)
        self.pushButton_open.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_open.setObjectName("pushButton_open")
        self.pushButton_save = QtWidgets.QPushButton(self.frame_menu_principal)
        self.pushButton_save.setGeometry(QtCore.QRect(115, 2, 80, 80))
        self.pushButton_save.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_save.setToolTipDuration(-2)
        self.pushButton_save.setStyleSheet("QPushButton{\n"
"    \n"
"    background-image: url(:/open/novosaveicone.png);\n"
"    background-color:transparent;\n"
"    background-repeat:no-repeat;\n"
"    background-position:center;\n"
"    background-size-height:80px;\n"
"    background-size-width:80px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 255, 255);    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.pushButton_save.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Icons/export2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon2)
        self.pushButton_save.setIconSize(QtCore.QSize(120, 100))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_ppd = QtWidgets.QPushButton(self.frame_menu_principal)
        self.pushButton_ppd.setGeometry(QtCore.QRect(220, 2, 80, 80))
        self.pushButton_ppd.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_ppd.setToolTipDuration(-2)
        self.pushButton_ppd.setStyleSheet("QPushButton{        \n"
"    background-image: url(:/open/FotoJet.png);\n"
"    background-position:center-up;\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 255, 255);    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.pushButton_ppd.setText("")
        self.pushButton_ppd.setIcon(icon)
        self.pushButton_ppd.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_ppd.setObjectName("pushButton_ppd")
        self.pushButton_ep = QtWidgets.QPushButton(self.frame_menu_principal)
        self.pushButton_ep.setGeometry(QtCore.QRect(330, 2, 80, 80))
        self.pushButton_ep.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_ep.setToolTipDuration(-2)
        self.pushButton_ep.setStyleSheet("QPushButton{\n"
"    \n"
"    background-image: url(:/open/poros_efetivos-removebg-preview-removebg-preview.png);\n"
"    background-position:center-up;\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 255, 255);    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.pushButton_ep.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/open/Icons/poros_efetivos-removebg-preview-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ep.setIcon(icon3)
        self.pushButton_ep.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_ep.setObjectName("pushButton_ep")
        self.label = QtWidgets.QLabel(self.frame_menu_principal)
        self.label.setGeometry(QtCore.QRect(28, 77, 47, 30))
        self.label.setStyleSheet("background-color: transparent;\n"
"font: 75 11pt \"Verdana\";\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_menu_principal)
        self.label_2.setGeometry(QtCore.QRect(122, 77, 65, 30))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Verdana\";\n"
"background-color: transparent;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_menu_principal)
        self.label_3.setGeometry(QtCore.QRect(236, 77, 47, 30))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"font: 75 11pt \"Verdana\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_menu_principal)
        self.label_4.setGeometry(QtCore.QRect(349, 77, 47, 30))
        self.label_4.setStyleSheet("font: 75 11pt \"Verdana\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: transparent;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton_infomation = QtWidgets.QPushButton(self.frame_menu_principal)
        self.pushButton_infomation.setGeometry(QtCore.QRect(550, 2, 80, 80))
        self.pushButton_infomation.setToolTip("Image Information")
        self.pushButton_infomation.setToolTipDuration(-2)
        self.pushButton_infomation.setStyleSheet("QPushButton{\n"
"    background-image: url(:/open/infoImage-removebg-preview~1.png);\n"
"    background-position:center-up;\n"
"    background-color:transparent;\n"
"    background-repeat:no-repeat;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 255, 255);    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.pushButton_infomation.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/open/Icons/infoImage-removebg-preview~1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_infomation.setIcon(icon4)
        self.pushButton_infomation.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_infomation.setObjectName("pushButton_infomation")
        self.pushButton_binary = QtWidgets.QPushButton(self.frame_menu_principal)
        self.pushButton_binary.setGeometry(QtCore.QRect(440, 2, 80, 80))
        self.pushButton_binary.setToolTipDuration(-2)
        self.pushButton_binary.setStyleSheet("QPushButton{\n"
"    background-image: url(:/open/bina.png);\n"
"    background-position:center-up;\n"
"    background-color:transparent;\n"
"    background-repeat:no-repeat;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 255, 255);    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.pushButton_binary.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/open/Icons/bina.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_binary.setIcon(icon5)
        self.pushButton_binary.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_binary.setObjectName("pushButton_binary")
        self.label_5 = QtWidgets.QLabel(self.frame_menu_principal)
        self.label_5.setGeometry(QtCore.QRect(440, 77, 80, 30))
        self.label_5.setStyleSheet("font: 75 11pt \"Verdana\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: transparent;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_menu_principal)
        self.label_6.setGeometry(QtCore.QRect(540, 77, 100, 30))
        self.label_6.setStyleSheet("font: 75 11pt \"Verdana\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: transparent;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.frame_menu_principal)
        self.frame_view = QtWidgets.QFrame(self.centralwidget)
        self.frame_view.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_view.sizePolicy().hasHeightForWidth())
        self.frame_view.setSizePolicy(sizePolicy)
        self.frame_view.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_view.setBaseSize(QtCore.QSize(0, 0))
        self.frame_view.setStyleSheet("background-color: rgb(160, 160, 160);")
        self.frame_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_view.setObjectName("frame_view")
        self.pushButton_2d_view = QtWidgets.QPushButton(self.frame_view)
        self.pushButton_2d_view.setGeometry(QtCore.QRect(1, 0, 80, 40))
        self.pushButton_2d_view.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_2d_view.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_2d_view.setFont(font)
        self.pushButton_2d_view.setStyleSheet("QPushButton{    \n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font: 75 11pt \"Verdana\";\n"
"    color: rgb(0, 0, 0);\n"
"    background-color:rgb(255, 255, 255);    \n"
"}")
        self.pushButton_2d_view.setObjectName("pushButton_2d_view")
        self.pushButton_3d_view = QtWidgets.QPushButton(self.frame_view)
        self.pushButton_3d_view.setGeometry(QtCore.QRect(82, 0, 80, 40))
        self.pushButton_3d_view.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_3d_view.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_3d_view.setFont(font)
        self.pushButton_3d_view.setStyleSheet("QPushButton{    \n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    font: 75 11pt \"Verdana\";\n"
"    background-color:rgb(255, 255, 255);    \n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.pushButton_3d_view.setObjectName("pushButton_3d_view")
        self.verticalLayout.addWidget(self.frame_view)
        self.frame_view_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_view_main.setStyleSheet("background-color: rgb(20, 20, 20);")
        self.frame_view_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_view_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_view_main.setObjectName("frame_view_main")
        self.frame_image = QtWidgets.QFrame(self.frame_view_main)
        self.frame_image.setGeometry(QtCore.QRect(19, 21, 811, 509))
        self.frame_image.setMinimumSize(QtCore.QSize(400, 200))
        self.frame_image.setMaximumSize(QtCore.QSize(900, 600))
        self.frame_image.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border: 3px solid rgb(160,160,160);")
        self.frame_image.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_image.setObjectName("frame_image")
        self.label_name_image = QtWidgets.QLabel(self.frame_image)
        self.label_name_image.setGeometry(QtCore.QRect(76, 20, 680, 20))
        self.label_name_image.setMinimumSize(QtCore.QSize(680, 20))
        self.label_name_image.setMaximumSize(QtCore.QSize(680, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_name_image.setFont(font)
        self.label_name_image.setStyleSheet("border:0px;\n"
"font: 75 11pt \"Verdana\";")
        self.label_name_image.setText("")
        self.label_name_image.setScaledContents(True)
        self.label_name_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_image.setObjectName("label_name_image")
        self.label_image = QtWidgets.QLabel(self.frame_image)
        self.label_image.setGeometry(QtCore.QRect(266, 50, 300, 300))
        self.label_image.setMaximumSize(QtCore.QSize(300, 300))
        self.label_image.setStyleSheet("border:2px solid rgb(160, 160, 160);")
        self.label_image.setText("")
        self.label_image.setScaledContents(True)
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.frame_setas = QtWidgets.QFrame(self.frame_image)
        self.frame_setas.setGeometry(QtCore.QRect(266, 360, 300, 60))
        self.frame_setas.setMaximumSize(QtCore.QSize(300, 60))
        self.frame_setas.setStyleSheet("border:0px;")
        self.frame_setas.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_setas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_setas.setObjectName("frame_setas")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_setas)
        self.horizontalLayout_4.setContentsMargins(-1, 3, 3, 0)
        self.horizontalLayout_4.setSpacing(9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_seta_esquerda = QtWidgets.QPushButton(self.frame_setas)
        self.pushButton_seta_esquerda.setEnabled(False)
        self.pushButton_seta_esquerda.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_seta_esquerda.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_seta_esquerda.setStyleSheet("QPushButton{\n"
"    background-image: url(:/open/pngwing.com.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position:center-low;\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(200, 200, 200);\n"
"    border:2px solid rgb(35, 35, 35);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(150, 150, 150);\n"
"}")
        self.pushButton_seta_esquerda.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/open/Icons/pngwing.com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_seta_esquerda.setIcon(icon6)
        self.pushButton_seta_esquerda.setIconSize(QtCore.QSize(60, 57))
        self.pushButton_seta_esquerda.setObjectName("pushButton_seta_esquerda")
        self.horizontalLayout_4.addWidget(self.pushButton_seta_esquerda)
        self.lineEdit_quantity = QtWidgets.QLineEdit(self.frame_setas)
        self.lineEdit_quantity.setEnabled(False)
        self.lineEdit_quantity.setMaximumSize(QtCore.QSize(70, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lineEdit_quantity.setFont(font)
        self.lineEdit_quantity.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(200, 200, 200);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(35, 35, 35);\n"
"}")
        self.lineEdit_quantity.setInputMask("")
        self.lineEdit_quantity.setMaxLength(4)
        self.lineEdit_quantity.setFrame(True)
        self.lineEdit_quantity.setCursorPosition(0)
        self.lineEdit_quantity.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_quantity.setClearButtonEnabled(False)
        self.lineEdit_quantity.setObjectName("lineEdit_quantity")
        self.horizontalLayout_4.addWidget(self.lineEdit_quantity)
        self.pushButton_seta_direita = QtWidgets.QPushButton(self.frame_setas)
        self.pushButton_seta_direita.setEnabled(False)
        self.pushButton_seta_direita.setMinimumSize(QtCore.QSize(60, 55))
        self.pushButton_seta_direita.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_seta_direita.setStyleSheet("QPushButton{\n"
"    background-image: url(:/open/pngwing-direita.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position:center-low;\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(200, 200, 200);\n"
"    border:2px solid rgb(35, 35, 35);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(150, 150, 150);\n"
"}")
        self.pushButton_seta_direita.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/open/Icons/pngwing-direita.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_seta_direita.setIcon(icon7)
        self.pushButton_seta_direita.setIconSize(QtCore.QSize(60, 57))
        self.pushButton_seta_direita.setObjectName("pushButton_seta_direita")
        self.horizontalLayout_4.addWidget(self.pushButton_seta_direita)
        self.frame_playPause = QtWidgets.QFrame(self.frame_image)
        self.frame_playPause.setGeometry(QtCore.QRect(266, 430, 300, 60))
        self.frame_playPause.setMinimumSize(QtCore.QSize(300, 60))
        self.frame_playPause.setMaximumSize(QtCore.QSize(300, 60))
        self.frame_playPause.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_playPause.setStyleSheet("border:0px;")
        self.frame_playPause.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_playPause.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_playPause.setObjectName("frame_playPause")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_playPause)
        self.horizontalLayout_2.setContentsMargins(20, 4, 20, 12)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_play = QtWidgets.QPushButton(self.frame_playPause)
        self.pushButton_play.setEnabled(False)
        self.pushButton_play.setMinimumSize(QtCore.QSize(70, 55))
        self.pushButton_play.setMaximumSize(QtCore.QSize(70, 50))
        self.pushButton_play.setStyleSheet("QPushButton{\n"
"    \n"
"    background-image: url(:/open/play.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position:center-low;\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(200, 200, 200);\n"
"    border:2px solid rgb(35, 35, 35);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(150, 150, 150);\n"
"}")
        self.pushButton_play.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/open/Icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_play.setIcon(icon8)
        self.pushButton_play.setIconSize(QtCore.QSize(70, 55))
        self.pushButton_play.setObjectName("pushButton_play")
        self.horizontalLayout_2.addWidget(self.pushButton_play)
        self.pushButton_pause = QtWidgets.QPushButton(self.frame_playPause)
        self.pushButton_pause.setEnabled(False)
        self.pushButton_pause.setMinimumSize(QtCore.QSize(70, 55))
        self.pushButton_pause.setMaximumSize(QtCore.QSize(70, 50))
        self.pushButton_pause.setStyleSheet("QPushButton{\n"
"    \n"
"    background-image: url(:/open/pause.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position:center-low;\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(200, 200, 200);\n"
"    border:2px solid rgb(35, 35, 35);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(150, 150, 150);\n"
"}")
        self.pushButton_pause.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/open/Icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_pause.setIcon(icon9)
        self.pushButton_pause.setIconSize(QtCore.QSize(70, 57))
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.horizontalLayout_2.addWidget(self.pushButton_pause)
        self.label_quantity_images = QtWidgets.QLabel(self.frame_image)
        self.label_quantity_images.setGeometry(QtCore.QRect(10, 470, 274, 20))
        self.label_quantity_images.setStyleSheet("border:0px;\n"
"font: 75 11pt \"Verdana\";")
        self.label_quantity_images.setText("")
        self.label_quantity_images.setScaledContents(True)
        self.label_quantity_images.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_quantity_images.setObjectName("label_quantity_images")
        self.label_7 = QtWidgets.QLabel(self.frame_view_main)
        self.label_7.setGeometry(QtCore.QRect(505, 530, 334, 20))
        self.label_7.setStyleSheet("font: 75 8pt \"Verdana\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.frame_view_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 850, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/menu_secundario/Icons/pasta_icon-removebg-preview~1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon10)
        self.actionOpen.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionOpen.setShortcutVisibleInContextMenu(True)
        self.actionOpen.setPriority(QtWidgets.QAction.NormalPriority)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSAve = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/menu_secundario/Icons/novosaveicone~1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSAve.setIcon(icon11)
        self.actionSAve.setObjectName("actionSAve")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/menu_secundario/Icons/quit-removebg-preview (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon12)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPPD = QtWidgets.QAction(MainWindow)
        self.actionPPD.setObjectName("actionPPD")
        self.actionEP = QtWidgets.QAction(MainWindow)
        self.actionEP.setObjectName("actionEP")
        self.actionPISA_Team = QtWidgets.QAction(MainWindow)
        self.actionPISA_Team.setObjectName("actionPISA_Team")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSAve)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuAbout.addAction(self.actionPPD)
        self.menuAbout.addAction(self.actionEP)
        self.menuAbout.addAction(self.actionPISA_Team)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_open, self.pushButton_save)
        MainWindow.setTabOrder(self.pushButton_save, self.pushButton_ppd)
        MainWindow.setTabOrder(self.pushButton_ppd, self.pushButton_ep)
        MainWindow.setTabOrder(self.pushButton_ep, self.pushButton_infomation)
        MainWindow.setTabOrder(self.pushButton_infomation, self.pushButton_binary)
        MainWindow.setTabOrder(self.pushButton_binary, self.pushButton_seta_esquerda)
        MainWindow.setTabOrder(self.pushButton_seta_esquerda, self.lineEdit_quantity)
        MainWindow.setTabOrder(self.lineEdit_quantity, self.pushButton_seta_direita)
        MainWindow.setTabOrder(self.pushButton_seta_direita, self.pushButton_play)
        MainWindow.setTabOrder(self.pushButton_play, self.pushButton_pause)
        MainWindow.setTabOrder(self.pushButton_pause, self.pushButton_2d_view)
        MainWindow.setTabOrder(self.pushButton_2d_view, self.pushButton_3d_view)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PISA - Porous Image Space Analysis"))
        self.pushButton_open.setToolTip(_translate("MainWindow", "Open Folder"))
        self.pushButton_save.setToolTip(_translate("MainWindow", "<html><head/><body><p>Save Folder</p></body></html>"))
        self.pushButton_ppd.setToolTip(_translate("MainWindow", "Predominant Pore Directions"))
        self.pushButton_ep.setToolTip(_translate("MainWindow", "Effective Pores"))
        self.label.setText(_translate("MainWindow", "Open"))
        self.label_2.setText(_translate("MainWindow", "Export"))
        self.label_3.setText(_translate("MainWindow", "PPD"))
        self.label_4.setText(_translate("MainWindow", "EP"))
        self.pushButton_binary.setToolTip(_translate("MainWindow", "Binarize Images"))
        self.label_5.setText(_translate("MainWindow", "Binarize"))
        self.label_6.setText(_translate("MainWindow", "I I"))
        self.pushButton_2d_view.setText(_translate("MainWindow", "2D View"))
        self.pushButton_3d_view.setText(_translate("MainWindow", "3D View"))
        self.label_7.setText(_translate("MainWindow", "Developers: Edvaldo Melo, Valci Júnior and Waldir Roque"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSAve.setText(_translate("MainWindow", "Save"))
        self.actionSAve.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionPPD.setText(_translate("MainWindow", "PPD"))
        self.actionEP.setText(_translate("MainWindow", "EP"))
        self.actionPISA_Team.setText(_translate("MainWindow", "PISA Team"))

